// React/00001-React-Nextjs-getStaticPathsでダイナミックルーティング/app/pages/index.tsx
import { GetStaticProps } from "next";
import { User } from "../interfaces/User";
import { userData } from "../data/users";
import Link from "next/link";

type Props = {
  items: User[];
};

const unko = ({ items }: Props) => (
  <ul>
    {items.map((item) => (
      <li key={item.id}>
        <Link href="/users/[id]" as={`/users/${item.id}`}>
          <a>
            {item.id}: {item.name}
          </a>
        </Link>
      </li>
    ))}
  </ul>
);
export default unko;

export const getStaticProps: GetStaticProps = async () => {
  const items: User[] = userData;
  return { props: { items } };
};

// Vue/00010-Vue-jQueryを使う/app/pages/index.vue
<template>
  <div>
    <ul>
      <li v-for="(item, key) of items" :key="key">
        <nuxt-link :to="item.to">
          <b-icon :icon="item.icon" /> {{ item.title }}
        </nuxt-link>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  data() {
    return {
      items: [
        {
          title: "Home",
          icon: "home",
          to: { name: "index" },
        },
        {
          title: "sketch-jquery",
          icon: "lightbulb",
          to: { name: "sketch-jquery" },
        },
      ],
    };
  },
};
</script>
